### PR TITLE
Fix hikari relocation

### PR DESCRIPTION
**Pull request by KaspianDev**
It's actually hikari, not hikaricp 😄

### CODE REVIEW

**Comment by Skyslycer** [comment]
??
https://mvnrepository.com/artifact/com.zaxxer/HikariCP/5.0.1

**Comment by lucian929** [comment]
> It's actually hikari, not hikaricp 😄

I checked maven central, it looks like HikariCP is correct: [https://search.maven.org/search?q=g:com.zaxxer]( https://search.maven.org/search?q=g:com.zaxxer).

**Comment by KaspianDev** [comment]
You can see yourself, if you build a jar using hikaricp groupid the dependency won't be relocated.

**Comment by Fisher2911** [comment]
I’ll take a look when I get home, thanks for pointing it out.

**Comment by KaspianDev** [comment]
@Fisher2911

**Comment by LoJoSho** [comment]
Closing this issue as it won't be merged with the Remapped version.

**Pull request closed without merging**
